import React, { useState, useEffect, useRef } from 'react';
import { Sparkles, ImagePlus, Zap, Image as ImageIcon, Download, Settings, Upload, X, Map, Users, Smartphone, Package, Palette, FastForward, Maximize2, Layers, Split, Film, ChevronRight, Save } from 'lucide-react';
import { cn } from '../../lib/utils';
import { useAppStore } from '../../store';
import { getApiUrl } from '../../config/apiConfig';
// Use your existing shorts hook & config
import { useShorts } from '../../hooks/useShorts';
import { SHORTS_COST } from '../../config/shortsConfig';

let savedScrollPosition = 0;

export const StoryboardView = ({
    activeFrame, frames, setFrames, setActiveFrameId, setMode, selections, setSelections,
    storyboardSlots, setStoryboardSlots, activeSlotId, setActiveSlotId, runAiUpscale, upscaling, selectedModel, downloadImage
}) => {
    // ─────────────────────────────────────────────
    // STATE
    // ─────────────────────────────────────────────
    const { token, updateShortsRaw, userProfile } = useAppStore();
    const { spend } = useShorts();

    // The user's uploaded/selected images for the scene
    const [sceneSettings, setSceneSettings] = useState({
        productImage: null,
        characterRef: null,
        styleRef: null,
    });

    const [sceneBrief, setSceneBrief] = useState(selections?.storyboardBrief || "");
    const [shotTimings, setShotTimings] = useState(selections?.storyboardTimings || "1.0, 1.5, 0.5, 2.0");

    const [isGenerating, setIsGenerating] = useState(false);

    // Active slot for preview/editing
    const activeSlot = storyboardSlots.find(s => s.id === activeSlotId);

    const fileInputRef = useRef(null);
    const [uploadTarget, setUploadTarget] = useState(null);

    const scrollContainerRef = useRef(null);

    // Restore scroll position on mount
    useEffect(() => {
        if (scrollContainerRef.current) {
            scrollContainerRef.current.scrollLeft = savedScrollPosition;
        }
    }, []);

    // Save scroll position on update
    const handleScroll = (e) => {
        savedScrollPosition = e.target.scrollLeft;
    };

    // ─────────────────────────────────────────────
    // AUTO-FILL FROM EXISTING SELECTIONS (Optional)
    // ─────────────────────────────────────────────
    // If the user already generated an image/video, carry it over as a product or char ref
    // Only auto-fill the HERO slot on initial mount:
    // - Skip if the slot already has a value
    // - Skip if the frame was generated by this view (multishot/storyboard type)
    useEffect(() => {
        if (
            activeFrame?.url &&
            !sceneSettings.productImage &&
            activeFrame.type !== 'multishot' &&
            activeFrame.type !== 'storyboard'
        ) {
            setSceneSettings(p => ({ ...p, productImage: activeFrame.url }));
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []); // Run once on mount only

    useEffect(() => {
        if (selections?.referenceImage && !sceneSettings.productImage) {
            setSceneSettings(p => ({ ...p, productImage: selections.referenceImage }));
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []); // Run once on mount only


    // ─────────────────────────────────────────────
    // HANDLERS
    // ─────────────────────────────────────────────
    const handleBriefChange = (val) => {
        setSceneBrief(val);
        setSelections(prev => ({ ...prev, storyboardBrief: val }));
    };

    const handleTimingsChange = (val) => {
        setShotTimings(val);
        setSelections(prev => ({ ...prev, storyboardTimings: val }));
    };

    const triggerUpload = (target) => {
        setUploadTarget(target);
        fileInputRef.current?.click();
    };

    const handleFileUpload = (e) => {
        const file = e.target.files?.[0];
        if (!file || !uploadTarget) return;

        const reader = new FileReader();
        reader.onloadend = () => {
            setSceneSettings(p => ({ ...p, [uploadTarget]: reader.result }));
            // Optional: Also auto-add to the main Pinboard/RefBoard if you want cross-persistence
        };
        reader.readAsDataURL(file);
    };

    const generateStoryboard = async () => {
        if (isGenerating) return;

        console.log("[STORYBOARD] Clicked generateStoryboard top handler.");
        console.log("[STORYBOARD] State:", { productImage: sceneSettings.productImage, sceneBrief: sceneBrief });

        if (!sceneSettings.productImage && !sceneBrief) {
            alert("Please provide at least a Hero/Product image or a brief description.");
            return;
        }

        // Set Loading Immediately for Instance Response Time!
        setIsGenerating(true);
        setStoryboardSlots(slots => slots.map(s => ({ ...s, loading: true, url: null })));

        const res = await spend('storyboard_gen');

        if (!res || !res.success) {
            // Restore loading if spend fails
            setIsGenerating(false);
            setStoryboardSlots(slots => slots.map(s => ({ ...s, loading: false })));

            if (res?.reason === 'unauthenticated') {
                useAppStore.getState().setShowingAuthModal(true);
            } else if (res?.reason === 'insufficient_funds' || useAppStore.getState().userShorts <= 0) {
                useAppStore.getState().setActiveTab('pricing');
            } else {
                alert("Storyboard generation could not proceed: " + (res?.reason || "error"));
            }
            return;
        }

        try {
            // NOTE: In a real app, you'd send `sceneSettings` and `sceneBrief` to your backend
            // which would return 4 (or N) distinct images and prompts.
            // For now, we simulate calling the standard image generator 4 times (or using a dedicated SB endpoint).

            // Generate a 3x3 grid using the multishot prompt technique
            const buildStoryboardPrompt = (sceneBrief, hasRefImage) => {
                const header = `A single composite image containing exactly 9 distinct cinematic photographs
arranged in a flawless 3x3 grid layout. Read left-to-right, top-to-bottom as a timeline.
Each row represents a new beat. High-end production value, dramatic lighting, full color.`;

                const subject = hasRefImage
                    ? `Take the subject and visual identity from the attached reference image exactly as-is.
Maintain 100% character continuity — the same subject must appear in all 9 frames 
experiencing the passage of time through this scene: ${sceneBrief || 'a cinematic story'}`
                    : `Scene: ${sceneBrief || 'a cinematic story'}`;

                const arc = `
Arrange the sequence chronologically from top-left (start) to bottom-right (end).

FRAME 1 (Top-Left):    ESTABLISHING — Wide angle. Setting the world and location.
FRAME 2 (Top-Center):  ARRIVAL — Subject enters the scene. Medium shot.
FRAME 3 (Top-Right):   TENSION BUILDS — Close-up. Emotional state becomes visible.
FRAME 4 (Mid-Left):    COMPLICATION — Something changes. Wide reaction shot.
FRAME 5 (Mid-Center):  THE PIVOT — Sudden change in action or emotion. Most dramatic frame.
FRAME 6 (Mid-Right):   TURNING POINT — Low angle. Power shift visible.
FRAME 7 (Bot-Left):    AFTERMATH — Medium shot. Consequences visible.
FRAME 8 (Bot-Center):  RESOLUTION — Wide shot. World has changed.
FRAME 9 (Bot-Right):   FINAL REACTION — Close-up. Emotional punctuation. End of story.`;

                const footer = `
STRICT VISUAL REQUIREMENTS:
- 9 distinct borderless frames in a single composite picture
- Each frame visually distinct in angle, lighting and composition
- Chronological story flow from Frame 1 to Frame 9
- Subject identity locked — same character in every frame
- Photorealistic cinematic quality throughout

CRITICAL — ZERO TEXT RULE: NO text, letters, labels, captions, shot type abbreviations,
scene numbers, or ANY written characters anywhere on any frame. Pure visual only.`;

                return `${header}\n\n${subject}\n${arc}\n${footer}`;
            };

            // IMPORTANT: Always use an image model, never the active video model.
            const IMAGE_MODEL = 'nano-banana-2';

            const payload = {
                prompt: buildStoryboardPrompt(
                    sceneBrief, 
                    !!sceneSettings.productImage || !!sceneSettings.characterRef
                ),
                model: IMAGE_MODEL,
                aspect_ratio: '16:9',
                image: sceneSettings.productImage || sceneSettings.characterRef || null,
                identity_images: [
                    sceneSettings.characterRef, 
                    sceneSettings.productImage
                ].filter(Boolean),
                references: [sceneSettings.styleRef].filter(Boolean),
                quality: '1k'
            };

            const res = await fetch(getApiUrl('/api/generate-image'), {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify(payload)
            });

            if (!res.ok) {
                const errData = await res.json().catch(() => ({}));
                throw new Error(errData.message || errData.error || "Storyboard generation failed");
            }
            const rawResult = await res.json();

            // Handle async job queue response (when Redis/BullMQ is active on server)
            let result;
            if (rawResult.jobId) {
                console.log(`[STORYBOARD] Server queued job: ${rawResult.jobId}. Polling...`);
                let url = null;
                const maxAttempts = 30;
                for (let i = 0; i < maxAttempts; i++) {
                    await new Promise(r => setTimeout(r, 2000));
                    try {
                        let pollRes;
                        try {
                            pollRes = await fetch(getApiUrl(`/api/job-status/${rawResult.jobId}`));
                        } catch (fetchErr) {
                            console.warn(`[STORYBOARD_POLL] Fetch failed (Attempt ${i}):`, fetchErr.message);
                            continue; // Retry on network error
                        }

                        if (!pollRes.ok) {
                            console.warn(`[STORYBOARD_POLL] Server error (Attempt ${i}):`, pollRes.statusText);
                            continue; // Retry on server error
                        }

                        const pollData = await pollRes.json();
                        const state = pollData.status || pollData.state;
                        if (state === 'completed' && pollData.url) { url = pollData.url; break; }
                        if (state === 'failed') throw new Error(pollData.error || 'Storyboard queue job failed');
                    } catch (e) {
                        if (e.message.includes('job failed')) throw e;
                        console.warn(`[STORYBOARD_POLL] Transient error (Attempt ${i}):`, e.message);
                    }
                }
                if (!url) throw new Error('Storyboard generation timed out.');
                result = { url };
            } else {
                result = rawResult;
            }

            if (!result.url) {
                throw new Error('Server returned no image URL and no jobId.');
            }

            // We only need one slot now representing the grid, but we keep the structure flexible
            // For now, we'll store the grid in the first slot and clear the others
            setStoryboardSlots([{
                id: 'slot-1',
                time: 0,
                duration: 'All Shots',
                prompt: `Auto-generated 3x3 storyboard grid`,
                loading: false,
                url: result.url || null,
                error: result.error,
                isGrid: true
            }]);

            // Also add these to the main film roll so they don't disappear
            if (result.url) {
                const newFrame = {
                    id: `sb-frame-${Date.now()}`,
                    url: result.url,
                    type: 'multishot',
                    model: 'storyboard',
                    loading: false,
                    prompt: `Storyboard 3x3 Grid`
                };
                setFrames(prev => [...prev, newFrame]);
            }

        } catch (error) {
            console.error("Storyboard generation error:", error);
            alert("Failed to generate storyboard. Check console.");
            setStoryboardSlots(slots => slots.map(s => ({ ...s, loading: false })));
        } finally {
            setIsGenerating(false);
        }
    };



    const handleDeleteSlot = (id, e) => {
        e.stopPropagation();
        const prevSlots = [...storyboardSlots];
        setStoryboardSlots(slots => slots.filter(s => s.id !== id));
        if (activeSlotId === id) {
            const remaining = prevSlots.filter(s => s.id !== id);
            setActiveSlotId(remaining.length > 0 ? remaining[0].id : null);
        }
    };

    // ─────────────────────────────────────────────
    // GRID INTERACTION LOGIC
    // ─────────────────────────────────────────────
    const gridImgRef = React.useRef(null);
    const gridContainerRef = React.useRef(null);

    // Calculate the actual rendered image bounds inside the object-contain container
    const getRenderedImageBounds = () => {
        const img = gridImgRef.current;
        const container = gridContainerRef.current;
        if (!img || !container) return null;
        const containerW = container.clientWidth;
        const containerH = container.clientHeight;
        const natW = img.naturalWidth;
        const natH = img.naturalHeight;
        if (!natW || !natH) return null;
        const scale = Math.min(containerW / natW, containerH / natH);
        const renderedW = natW * scale;
        const renderedH = natH * scale;
        const offsetX = (containerW - renderedW) / 2;
        const offsetY = (containerH - renderedH) / 2;
        return { offsetX, offsetY, renderedW, renderedH };
    };

    const handleCellClick = (row, col) => {
        const img = gridImgRef.current;
        if (!img) return;
        const cellW = img.naturalWidth / 3;
        const cellH = img.naturalHeight / 3;
        const canvas = document.createElement('canvas');
        canvas.width = cellW;
        canvas.height = cellH;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, col * cellW, row * cellH, cellW, cellH, 0, 0, cellW, cellH);

        const croppedUrl = canvas.toDataURL('image/jpeg', 0.9);
        const shotNumber = (row * 3) + col + 1;

        // Add the extracted shot to the timeline and main film roll
        const newSlot = {
            id: `sb-shot-${Date.now()}`,
            time: 0,
            duration: '1.0s',
            prompt: sceneBrief ? `${sceneBrief} (Shot ${shotNumber})` : `Shot ${shotNumber} from grid`,
            loading: false,
            url: croppedUrl,
            error: false,
            isGrid: false
        };

        setStoryboardSlots(prev => [...prev, newSlot]);
        setActiveSlotId(newSlot.id);

        setFrames(prev => [...prev, {
            id: `sb-frame-crop-${Date.now()}`,
            url: croppedUrl,
            type: 'image',
            model: 'storyboard',
            loading: false,
            prompt: `Storyboard Shot ${shotNumber}`
        }]);
    };

    // Recompute overlay position on image load and window resize
    const [overlayStyle, setOverlayStyle] = useState({});
    const updateOverlay = () => {
        const bounds = getRenderedImageBounds();
        if (bounds) {
            setOverlayStyle({
                position: 'absolute',
                left: `${bounds.offsetX}px`,
                top: `${bounds.offsetY}px`,
                width: `${bounds.renderedW}px`,
                height: `${bounds.renderedH}px`,
            });
        }
    };

    // ─────────────────────────────────────────────
    // RENDER
    // ─────────────────────────────────────────────
    return (
        <div className="flex-1 flex flex-col lg:flex-row gap-4 h-full overflow-hidden p-2 md:p-0">
            <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={handleFileUpload} />

            {/* ── LEFT COLUMN: Setup & Brief ── */}
            <div className="w-full lg:w-[28%] min-w-[280px] flex flex-col gap-2 overflow-y-auto custom-scrollbar pr-1">

                <div className="surface-glass rounded-2xl p-4 md:p-5 flex flex-col gap-4 border border-white/5 flex-1">
                    <h3 className="text-sm md:text-xs font-black text-white uppercase flex items-center gap-2">
                        <Layers className="w-5 h-5 md:w-4 md:h-4 text-[#D4FF00]" />
                        Concept & Refs
                    </h3>

                    {/* Reference Slots */}
                    <div className="grid grid-cols-3 gap-2 md:gap-1.5">
                        {[
                            { id: 'productImage', label: 'HERO', icon: Package },
                            { id: 'characterRef', label: 'CHAR', icon: Users },
                            { id: 'styleRef', label: 'STYLE', icon: Palette },
                        ].map(ref => (
                            <div key={ref.id} className="relative group aspect-square rounded-lg overflow-hidden border border-dashed border-white/10 hover:border-white/30 transition-all cursor-pointer bg-black/40">
                                {sceneSettings[ref.id] ? (
                                    <>
                                        <img src={sceneSettings[ref.id]} className="w-full h-full object-cover" />
                                        <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                                            <button onClick={() => triggerUpload(ref.id)} className="p-1.5 bg-white/20 hover:bg-white/40 rounded-md"><Upload className="w-3 h-3 text-white" /></button>
                                            <button onClick={() => setSceneSettings(p => ({ ...p, [ref.id]: null }))} className="p-1.5 bg-red-500/80 hover:bg-red-500 rounded-md"><X className="w-3 h-3 text-white" /></button>
                                        </div>
                                    </>
                                ) : (
                                    <div onClick={() => triggerUpload(ref.id)} className="absolute inset-0 flex flex-col items-center justify-center gap-1 opacity-40 group-hover:opacity-100 transition-opacity">
                                        <ref.icon className="w-4 h-4" />
                                        <span className="text-[8px] font-bold uppercase tracking-widest">{ref.label}</span>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>

                    <div className="flex flex-col gap-1.5">
                        <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">Scene Brief / Script</label>
                        <textarea
                            value={sceneBrief}
                            onChange={e => handleBriefChange(e.target.value)}
                            placeholder="Describe the overall narrative or paste a script snippet..."
                            className="w-full h-24 bg-black/40 border border-white/10 rounded-xl p-3 text-sm text-white resize-none focus:border-[#D4FF00]/50 outline-none"
                        />
                    </div>

                    <div className="flex flex-col gap-1.5">
                        <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">Shot Timings (Seconds)</label>
                        <input
                            type="text"
                            value={shotTimings}
                            onChange={e => handleTimingsChange(e.target.value)}
                            placeholder="e.g. 1.0, 1.5, 2.0"
                            className="w-full bg-black/40 border border-white/10 rounded-xl p-2.5 text-xs text-white outline-none"
                        />
                    </div>

                    {/* Spacer to push button downwards */}
                    <div className="flex-1" />

                    <button
                        onClick={generateStoryboard}
                        disabled={isGenerating}
                        className={cn("w-full py-4 rounded-xl flex items-center justify-center gap-2 font-black uppercase tracking-wider shadow-2xl transition-all",
                            isGenerating ? "bg-white/10 text-white/50 cursor-not-allowed" : "bg-[#D4FF00] hover:bg-white text-black")}
                    >
                        {isGenerating ? <Zap className="w-4 h-4 animate-pulse" /> : <Split className="w-4 h-4" />}
                        {isGenerating ? 'Drafting 9-Shot Grid...' : 'Draft 3x3 Storyboard Grid'}
                    </button>
                    {(SHORTS_COST.image_grid_multishot || 2) > 0 && (
                        <div className="text-center text-[9px] font-bold text-white/30 uppercase mt-[-8px]">
                            Costs {SHORTS_COST.image_grid_multishot || 2} Shorts
                        </div>
                    )}
                </div>
            </div>


            {/* ── RIGHT COLUMN: Spline / Preview Area ── */}
            <div className="flex-1 flex flex-col gap-2 min-h-0">

                {/* Active View / Main Editing */}
                <div className="flex-[2] surface-glass rounded-2xl border flex flex-col overflow-hidden relative"
                    style={{ borderColor: activeSlot?.url ? '#D4FF00' : 'rgba(255,255,255,0.05)' }}>

                    <div className="absolute top-4 left-4 z-10 bg-black/60 backdrop-blur-md px-3 py-1.5 rounded-lg border border-white/10 flex items-center gap-2">
                        <span className="text-[11px] md:text-[10px] font-black text-[#D4FF00] uppercase tracking-wider">
                            {activeSlot?.isGrid ? '3x3 Master Grid' : `Shot ${storyboardSlots.indexOf(activeSlot)}`}
                        </span>
                        <div className="w-1 h-1 rounded-full bg-white/20" />
                        <span className="text-[10px] md:text-[9px] text-white/50">{activeSlot?.duration || '1.0s'}</span>
                    </div>

                    {activeSlot?.url ? (
                        <>
                            <div ref={gridContainerRef} className="relative w-full h-full flex items-center justify-center">
                                <img
                                    src={activeSlot.url}
                                    ref={activeSlot.isGrid ? gridImgRef : null}
                                    className="w-full h-full object-contain bg-black/40"
                                    crossOrigin="anonymous"
                                    onLoad={updateOverlay}
                                />

                                {/* 3x3 Overlay for Master Grid Selection — aligned to actual image bounds */}
                                {activeSlot.isGrid && overlayStyle.width && (
                                    <div style={overlayStyle} className="z-10">
                                        <div className="w-full h-full grid grid-cols-3 grid-rows-3" style={{ pointerEvents: 'auto' }}>
                                            {[...Array(9)].map((_, i) => (
                                                <div key={i} onClick={() => handleCellClick(Math.floor(i / 3), i % 3)}
                                                    className="cursor-pointer border border-white/5 transition-all flex items-center justify-center group/cell hover:bg-white/[0.15]"
                                                    onMouseEnter={e => e.target.style.background = 'rgba(255,255,255,0.15)'}
                                                    onMouseLeave={e => e.target.style.background = 'transparent'}>
                                                    <span className="text-[9px] md:text-[8px] font-black text-white/0 group-hover/cell:text-[#D4FF00] uppercase tracking-widest px-2 py-1 rounded group-hover/cell:scale-110 transition-transform text-center">
                                                        Extract <br className="md:hidden" /> Shot {i + 1}
                                                    </span>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                            </div>

                            <div className="absolute right-4 top-4 flex flex-col gap-2 z-20">
                                {!activeSlot.isGrid && (
                                    <>
                                        <button 
                                            onClick={() => runAiUpscale(activeSlot.url, activeSlot.prompt || '', 'storyboard')} 
                                            disabled={upscaling || activeSlot.loading} 
                                            className={cn("p-3 bg-fuchsia-600 hover:bg-fuchsia-500 rounded-xl text-white shadow-xl group flex items-center justify-center gap-2 transition-all", (upscaling || activeSlot.loading) && "opacity-50 cursor-not-allowed")}
                                        >
                                            <Sparkles className={cn("w-4 h-4 md:w-5 md:h-5", (upscaling || activeSlot.loading) && "animate-pulse")} />
                                            <span className="text-[10px] font-black uppercase md:w-0 overflow-hidden md:group-hover:w-auto transition-all whitespace-nowrap">{(upscaling || activeSlot.loading) ? 'Upscaling...' : 'Upscale 2K (2 Credits)'}</span>
                                        </button>
                                        <button 
                                            onClick={() => { setSelections(p => ({ ...p, firstFrame: activeSlot.url, subject: activeSlot.prompt || sceneBrief })); setMode('video') }}
                                            className="p-3 bg-[#D4FF00]/90 hover:bg-[#D4FF00] rounded-xl text-black shadow-xl group flex items-center gap-2 transition-all"
                                            title="Set as First Frame"
                                        >
                                            <Film className="w-4 h-4" />
                                            <span className="text-[10px] font-black uppercase w-0 overflow-hidden group-hover:w-auto transition-all whitespace-nowrap">First Frame</span>
                                        </button>
                                        <button 
                                            onClick={() => { setSelections(p => ({ ...p, lastFrame: activeSlot.url, subject: activeSlot.prompt || sceneBrief })); setMode('video') }}
                                            className="p-3 bg-purple-500 hover:bg-purple-400 rounded-xl text-white shadow-xl group flex items-center gap-2 transition-all"
                                            title="Set as Last Frame"
                                        >
                                            <FastForward className="w-4 h-4" />
                                            <span className="text-[10px] font-black uppercase w-0 overflow-hidden group-hover:w-auto transition-all whitespace-nowrap">Last Frame</span>
                                        </button>
                                    </>
                                )}
                                <button onClick={() => downloadImage(activeSlot.url)} className="p-3 bg-white/10 hover:bg-white/20 backdrop-blur-md rounded-xl text-white transition-all">
                                    <Download className="w-4 h-4" />
                                </button>
                            </div>

                            {/* Prompt overlay */}
                            {!activeSlot.isGrid && (
                                <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black via-black/80 to-transparent p-6 pt-12 z-20 pointer-events-none">
                                    <input
                                        value={activeSlot.prompt}
                                        style={{ pointerEvents: 'auto' }}
                                        onChange={(e) => {
                                            setStoryboardSlots(slots => slots.map(s => s.id === activeSlotId ? { ...s, prompt: e.target.value } : s));
                                        }}
                                        className="w-full bg-transparent text-white text-sm border-b border-white/10 pb-1 focus:border-[#D4FF00] outline-none placeholder:text-white/20 transition-colors"
                                        placeholder="Enter specific prompt for this shot..."
                                    />
                                </div>
                            )}
                        </>
                    ) : (
                        <div className="w-full h-full flex flex-col items-center justify-center gap-3 opacity-20">
                            {activeSlot?.loading ? (
                                <>
                                    <Sparkles className="w-10 h-10 text-[#D4FF00] animate-spin" />
                                    <p className="text-xs font-bold uppercase tracking-widest animate-pulse">Drafting 3x3 Grid...</p>
                                </>
                            ) : (
                                <>
                                    <Split className="w-10 h-10 text-white" />
                                    <p className="text-xs font-bold uppercase tracking-widest">Awaiting Generation</p>
                                </>
                            )}
                        </div>
                    )}
                </div>

                {/* Timeline / Slidertray */}
                <div className="h-40 shrink-0 surface-glass rounded-2xl border border-white/5 p-3 flex flex-col">
                    <div className="flex items-center justify-between mb-2 px-1">
                        <span className="text-[9px] font-black text-white/40 uppercase tracking-widest">Timeline Sequence</span>
                        <div className="flex gap-1">
                            <button className="px-2 py-1 bg-white/5 hover:bg-white/10 rounded-md text-[8px] font-bold text-white uppercase">+ Add Shot</button>
                        </div>
                    </div>

                    <div 
                        ref={scrollContainerRef}
                        onScroll={handleScroll}
                        className="flex-1 flex gap-2 overflow-x-auto custom-scrollbar pb-1"
                    >
                        {storyboardSlots.map((slot, idx) => (
                            <div key={slot.id}
                                onClick={() => setActiveSlotId(slot.id)}
                                className={cn("shrink-0 h-full aspect-video rounded-xl overflow-hidden cursor-pointer relative border-2 transition-all group",
                                    activeSlotId === slot.id ? "border-[#D4FF00] shadow-[0_0_15px_rgba(212,255,0,0.15)]" : "border-white/5 hover:border-white/20")}>
                                {slot.loading ? (
                                    <div className="w-full h-full bg-black/40 flex items-center justify-center">
                                        <Zap className="w-4 h-4 text-[#D4FF00] animate-pulse" />
                                    </div>
                                ) : slot.url ? (
                                    <>
                                        <img src={slot.url} className="w-full h-full object-cover" />


                                        {/* Corner Delete Button */}
                                        <button 
                                            onClick={(e) => handleDeleteSlot(slot.id, e)}
                                            className="absolute top-1 right-1 p-1 bg-red-600/80 hover:bg-red-500 backdrop-blur-md rounded text-white opacity-0 group-hover:opacity-100 hover:scale-110 transition-all shadow-lg z-10"
                                            title="Remove Frame"
                                        >
                                            <X className="w-3 h-3" />
                                        </button>
                                    </>
                                ) : (
                                    <div className="w-full h-full bg-black/40 flex flex-col items-center justify-center gap-1 opacity-50">
                                        <span className="text-lg font-black text-white/20">{idx + 1}</span>
                                    </div>
                                )}

                                <div className="absolute inset-x-0 bottom-0 bg-black/80 px-2 py-1 flex items-center justify-between backdrop-blur-sm">
                                    <span className="text-[8px] font-black text-[#D4FF00]">S{idx + 1}</span>
                                    <span className="text-[8px] font-bold text-white/60">{slot.duration}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

            </div>
        </div>
    );
};
